site_name: Deeson Handbook
theme_dir: deeson-theme/deeson-theme
repo_url: https://github.com/teamdeeson/codex
include_search: true
site_favicon: images/favicon.ico
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />The Deeson Handbook is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
pages:
- Home: index.md
- Basics:
    - Principles and values: handbook/principles-and-values.md
    - Self-organisation: handbook/self-organisation.md
    - Accountabilities and teams: handbook/accountabilities-and-teams.md
    - Roles at Deeson: handbook/roles-at-deeson.md
    - Teams: handbook/teams.md
    - Company-wide tools, processes and policies: handbook/tools-processes-policies.md
- Guides:
    - Joining Deeson: working-at-deeson/joining-deeson.md
    - Where and when we work: working-at-deeson/where-and-when-we-work.md
    - Self-scheduling: working-at-deeson/self-scheduling.md
    - Personal goals and development: working-at-deeson/personal-goals-and-development.md
    - Tools, purchasing and equipment: working-at-deeson/tools-purchasing-and-equipment.md
    - Subscriptions: working-at-deeson/subscriptions.md
    - Time recording: working-at-deeson/time-recording.md
    - Pay, benefits, expenses and recruitment bonus: working-at-deeson/pay-benefits-and-expenses.md
    - Pay review: working-at-deeson/pay-review.md
    - Time off: working-at-deeson/taking-leave.md
    - Sabbaticals: working-at-deeson/sabbaticals.md
    - Attending conferences: company-policies/conference-policy.md
    - Deeson offices: working-at-deeson/deeson-offices.md
    - Useful links: working-at-deeson/useful-links.md
    - User guides: working-at-deeson/user-guides.md
- The Deeson OS:
    - Introduction: working-at-deeson/os-intro.md
    - Strategic planning: working-at-deeson/os-sp.md
    - Tracking progress: working-at-deeson/os-tracking.md
- Company policies:
    - Equality policy: company-policies/equality-policy.md
    - Social media policy: company-policies/social-media-policy.md
    - Sickness absence policy: company-policies/sickness-absence-policy.md
    - Disciplinary policy: company-policies/disciplinary-policy.md
    - Computer usage and security policy: company-policies/computer-usage-and-security-policy.md
    - Health & safety policy: company-policies/health-and-safety-policy.md
    - Environmental policy: company-policies/environmental-policy.md
    - Anti-bribery policy: company-policies/anti-bribery-policy.md
- Hosting:
    - Non-standard environments: hosting/non-standard-environments.md    
- Development:
    - Our Approach: development/approach.md
    - Local development: development/vdd.md
    - Front end: development/frontend.md
    - Drupal 7: development/drupal7.md
    - Drupal 8: development/drupal8.md
    - Security: development/security.md
    - git: development/git.md
    - Makefiles: development/makefiles.md
    - Coder lounge: development/coder-lounge.md
    - Brown bags: development/brown-bags.md
    - Jira: development/jira.md
    - Handover comms: development/handover.md
    - PHP Storm Config: development/php-storm-config.md
    - Learning resources: development/learning-resources.md
