site_name: Deeson Handbook
theme: readthedocs
repo_url: https://github.com/teamdeeson/codex
pages:
- Home: index.md
- About: about.md
- The basics:
    - Principles and values: handbook/principles-and-values.md
    - Self-organisation: handbook/self-organisation.md
    - Accountabilities and teams: handbook/accountabilities-and-teams.md
    - Roles at Deeson: handbook/roles-at-deeson.md
    - Pods: handbook/pods.md
    - Chapters: handbook/chapters.md
    - Company-wide tools, processes and policies: handbook/tools-processes-policies.md
- Working at Deeson:
    - Joining Deeson: working-at-deeson/joining-deeson.md
    - Where and when we work: working-at-deeson/where-and-when-we-work.md
    - Personal goals and development: working-at-deeson/personal-goals-and-development.md
    - Tools, purchasing and equipment: working-at-deeson/tools-purchasing-and-equipment.md
    - Pay, benefits and expenses: working-at-deeson/pay-benefits-and-expenses.md
    - Taking leave: working-at-deeson/taking-leave.md
    - Deeson offices: working-at-deeson/canterbury-office.md
    - Useful links: working-at-deeson/useful-links.md
    - Q&A: working-at-deeson/questions-and-answers.md
- Development:
    - Our Approach: development/approach.md
    - Local development: development/vdd.md
    - Front end: development/frontend.md
    - Drupal 7: development/drupal7.md
    - Drupal 8: development/drupal8.md
    - Symfony: development/symfony.md
    - git: development/git.md
    - Makefiles: development/makefiles.md
    - Deployment: development/deployment.md
    - Coder lounge: development/coder-lounge.md
    - Brown bags: development/brown-bags.md
    - Jira: development/jira.md
    - Handover comms: development/handover.md
- Discovery: discovery.md
