site_name: Deeson Handbook
theme_dir: deeson-theme/deeson-theme
repo_url: https://github.com/teamdeeson/codex
include_search: true
site_favicon: images/favicon.ico
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />The Deeson Handbook is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
pages:
- Home: index.md
- Basics:
    - Principles and values: handbook/principles-and-values.md
    - Teams: handbook/teams.md
    - Self-organisation: handbook/self-organisation.md
    - Personal accountability: handbook/accountabilities-and-teams.md
    - Job roles: handbook/roles-at-deeson.md
    - Tools, processes and policies: handbook/tools-processes-policies.md 
- Project delivery:
    - Our delivery process: handbook/our-delivery-process.md
    - Project roles: handbook/project-roles.md
- Recruitment:
    - Pay for new starters: working-at-deeson/new-starter-pay.md
    - Onboarding: working-at-deeson/joining-deeson.md
- Team member benefits:
    - Pay: working-at-deeson/pay-scales.md
    - Fair pay guarantee: working-at-deeson/fair-pay.md
    - Holidays and time off: working-at-deeson/taking-leave.md
    - Wellness fund: working-at-deeson/wellness.md
    - Equipment budget: working-at-deeson/equipment.md
    - Recruitment bonus: working-at-deeson/recruitment-bonus.md
    - Company pension: working-at-deeson/pension.md
    - Unlimited training budget: working-at-deeson/training.md
    - Peer recognition scheme: working-at-deeson/peer-recognition.md
    - Tax-free cycles and e-cycles: working-at-deeson/cycles.md
    - Charity work and volunteering: working-at-deeson/charity-volunteering.md
    - Paid sabbaticals: working-at-deeson/sabbaticals.md
- Personal development:
    - Monthly 1 to 1: working-at-deeson/one-to-ones.md
    - Professional development plan (PDP): working-at-deeson/pdp.md
    - Impact scoring: working-at-deeson/impact-scoring.md
- Working at Deeson:
    - Where and when we work: working-at-deeson/where-and-when-we-work.md
    - Self-scheduling: working-at-deeson/self-scheduling.md
    - Pay review: working-at-deeson/pay-review.md
    - Promotion or changing roles: working-at-deeson/promotion.md
    - Guide to maternity, paternity and shared parental leave: working-at-deeson/maternity-paternity-and-shared-leave-guide.md
    - Tools, purchasing and equipment: working-at-deeson/tools-purchasing-and-equipment.md
    - Subscriptions: working-at-deeson/subscriptions.md
    - Time recording: working-at-deeson/time-recording.md
    - Attending conferences: company-policies/conference-policy.md
    - London office: working-at-deeson/deeson-office-london.md
    - Canterbury office: working-at-deeson/deeson-office-london.md
    - TOG co-working spaces: working-at-deeson/coworking.md
    – Writing style guide: working-at-deeson/writing-guide.md
    - Useful links: working-at-deeson/useful-links.md    
- Company policies:
    - Equality policy: company-policies/equality-policy.md
    - Social media policy: company-policies/social-media-policy.md
    - Sickness absence policy: company-policies/sickness-absence-policy.md
    - Disciplinary policy: company-policies/disciplinary-policy.md
    - Computer usage and security policy: company-policies/computer-usage-and-security-policy.md
    - Health & safety policy: company-policies/health-and-safety-policy.md
    - Environmental policy: company-policies/environmental-policy.md
    - Anti-bribery policy: company-policies/anti-bribery-policy.md
    - Maternity, paternity & shared leave policy: company-policies/maternity-and-paternity-policy.md
    - Modern slavery: company-policies/modern-slavery.md
