site_name: Deeson Codex
theme: readthedocs
repo_url: https://github.com/teamdeeson/codex
include_search: true
pages:
- Home: index.md
- About: about.md
- Deeson Handbook: handbook.md
- Company: company.md
- Development:
    - Our Approach: development/approach.md
    - Front end: development/frontend.md
    - Drupal 7: development/drupal7.md
    - Drupal 8: development/drupal8.md
    - Symfony: development/symfony.md
    - git: development/git.md
    - Make files: development/makefiles.md
    - Deployment: development/deployment.md
    - Coder lounge: development/coder-lounge.md
    - Brown bags: development/brown-bags.md
    - Jira: development/jira.md
- Discovery: discovery.md
